export default {
  vaultNotesPath: "/Users/mnerger/obsidian/Writing",
  astroPath: "/Users/mnerger/code/konger-astro/src/pages/posts",
  dailiesDir: "periodic/dailies/",
  weekliesDir: "periodic/weeklies/",
  monthliesDir: "generated/",
  recipesDir: "recipe/",
  booksDir: "media/book/",
  sectionsToPull: [
    "Work",
    "Writing",
    "Projects",
    "Books",
    "Music",
    "Movie",
    "TV",
    "Podcast",
    "Game",
    "Video",
    "Other",
  ],
  firstDayString: "July 28 25",
};
