export default {
  vaultNotesPath: "/Users/j/obsidian/Writing",
  astroPath: "/Users/j/notes.d/projects/astro-blog/src/",
  dailiesDir: "periodic/dailies/",
  weekliesDir: "periodic/weeklies/",
  monthliesDir: "generated/",
  yearliesDir: "generated/",
  recipesDir: "recipe/",
  booksDir: "media/book/",
  sectionsToPull: [
    "Work",
    "Writing",
    "Projects",
    "Books",
    "Music",
    "Movie",
    "TV",
    "Podcast",
    "Game",
    "Video",
    "Other",
  ],
  firstDayString: "Dec 22 2025",
};
